const List<String> indianCities = [
  'Agra',
  'Ahmedabad',
  'Ajmer',
  'Aligarh',
  'Allahabad',
  'Amritsar',
  'Aurangabad',
  'Bangalore',
  'Bareilly',
  'Bhopal',
  'Bhubaneswar',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Faridabad',
  'Ghaziabad',
  'Gorakhpur',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Hubli',
  'Hyderabad',
  'Indore',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jamshedpur',
  'Jodhpur',
  'Kanpur',
  'Kochi',
  'Kolkata',
  'Kozhikode',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangalore',
  'Meerut',
  'Mumbai',
  'Mysore',
  'Nagpur',
  'Nashik',
  'New Delhi',
  'Noida',
  'Patna',
  'Pune',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Udaipur',
  'Varanasi',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
];

const List<String> indianAirports = [
  'Chhatrapati Shivaji Maharaj International Airport, Mumbai',
  'Indira Gandhi International Airport, Delhi',
  'Kempegowda International Airport, Bangalore',
  'Rajiv Gandhi International Airport, Hyderabad',
  'Chennai International Airport',
  'Netaji Subhas Chandra Bose International Airport, Kolkata',
  'Cochin International Airport',
  'Sardar Vallabhbhai Patel International Airport, Ahmedabad',
  'Pune Airport',
  'Jaipur International Airport',
  'Goa International Airport',
  'Coimbatore International Airport',
  'Trivandrum International Airport',
  'Calicut International Airport',
  'Mangalore International Airport',
];
